export const SIGNIN_USERS_REQUEST = "SIGNIN_USERS_REQUEST" ;
export const SIGNIN_USERS_SUCCESS = "SIGNIN_USERS_SUCCESS" ;
export const SIGNIN_USERS_FAILURE = "SIGNIN_USERS_FAILURE" ;

export const SIGNUP_USERS_REQUEST = "SIGNUP_USERS_REQUEST" ;
export const SIGNUP_USERS_SUCCESS = "SIGNUP_USERS_SUCCESS" ;
export const SIGNUP_USERS_FAILURE = "SIGNUP_USERS_FAILURE" ;